# This is a basic workflow to help you get started with Actions

name: smzdm bot

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  schedule:
  #定时任务，每10分钟一次
    - cron: '20 5 * * *'


jobs:


  build:
  
    runs-on: ubuntu-latest

    # 1. 首先copy git仓库到虚拟机上
    steps:

    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        
        if [ -f mistep.txt ]; then pip install -r mistep.txt; fi
    # 2. 执行仓库中的脚本文件
    - name: 'Change step'
      run: python ./mistep2w.py
