# This is a basic workflow to help you get started with Actions

name: smzdm bot

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  schedule:
  #定时任务，每10分钟一次
    - cron: '*/10 * * * *'
  #pull_request:
    #branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # 1. 首先copy git仓库到虚拟机上
    steps:
#    - name: 'Checkout codes'
#      uses: actions/checkout@v1
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # 2. 执行仓库中的脚本文件
    - name: 'Get smzdm'
      run: python ./smzdm.py
